---
title: "Workflow"
subtitle: "Sequential Steps"
bibliography: []
biblio-style: apalike
link-citations: yes
editor_options: 
  markdown: 
    wrap: 80
---

```{r, include = FALSE}
source(file.path(usethis::proj_get(), "vignettes",  "_common.R"))
path <- tempfile("docs-")
dir.create(path, F, T)
```

## Generating Boilerplate Workflow

```{r, eval = FALSE, echo = TRUE}
add_workflow(name = "order-one-pizza", domain = "pizza ordering", n_step = 3)
```

```{r, eval = TRUE, echo = FALSE}
withr::with_dir(
    path,
    add_workflow(name = "order-one-pizza", domain = "pizza ordering", n_step = 3)
)
file_path <- list.files(path, "order-one-pizza.R", recursive = TRUE)
```

Given `n_step = 3`, when you call `add_workflow`, then the function:

* Creates a workflow boilerplate with three steps;
* Places the file under ``r dirname(file_path)``; and
* Opens the file (only in interactive mode).

The boilerplate code looks likes this:

```{r code =  readLines(fs::path(path, file_path)), eval=FALSE, echo=TRUE}
```

