---
title: "Overview"
editor_options: 
  markdown: 
    wrap: 80
---

```{r, include = FALSE}
source(file.path(usethis::proj_get(), "vignettes",  "_common.R"))
```

## Hurry please, I have a short attention span, what is `ddd`?

Sorry, most likely `ddd` is not for you.

## Who is `ddd` for?

Here are a few assumptions about you:

-   You are an R user

-   You are an experienced Data Scientist

-   You have seen and created clunkers, that is, analytic applications with an
    abundance of cruft

-   You have a passion for producing analytic applications of high-quality every
    day

If you belong to the intersection of all the sets above, then ddd may benefit
you.

## What `ddd` is (but first, what it is not)

Because `ddd` is an R package that caters for Data Scientists, it is natural to
think it may contain a new learning algorithm, statistical method, a
visualisation tool, or data processing toolkit. `ddd` offers none of these
things. Instead, `ddd` automates repetitive tasks that arise during software
development in R. In that sense, `ddd` is akin to the
[`usethis`](https://usethis.r-lib.org/) package.

`ddd` is an acronym of a software development approach called [***Domain-driven
design***](https://en.wikipedia.org/wiki/Domain-driven_design), or DDD for
short. `ddd` facilitates the implementation of key DDD patterns including
Entity, Value Object and Domain Services. Together these building blocks form a
domain model.

Before getting into specifics about **Domain-driven Design**, lets first discuss
the importance of software design and how it is inevitable.

## Why should I use software design?

When you drive to a new place, especially if the destination is far or in an
unfamiliar location, something guides you. It could be a GPS, a map or a friend
sitting in the front seat. Have you ever tried driving to a new location without
any guidance? If so, how well did it go for you?

When you develop software to solve a new business problem, what guides your
software design? Obviously, you strive to eliminate unintended behaviors (bugs)
from the software. Perhaps you are using tests and even a Test-Driven
Development (TDD) approach. However, guiding your design with tests is analogous
to driving a car by using the guardrails. It keeps you safe from the bar ditches
while you drive, though it has no navigation utility.

<!-- Although each domain model is different, many patterns occur repeatedly. -->
