add_step("start_order", domain = "pizza_ordering")
add_step("add_pizza_to_order", domain = "pizza_ordering")
add_step("select_pizza_size", domain = "pizza_ordering")
add_step("add_topping", domain = "pizza_ordering")
add_step("remove_topping", domain = "pizza_ordering")
add_step("review_pizza", domain = "pizza_ordering")
add_step("confirm_order", domain = "pizza_ordering")
